import Teacher,{promote} from "./ teacher";
import React, {Component} from 'react';
 // default -> import ... from ...
 // Named -> import {..} from...
const teacher = new Teacher('Mosh',"MSc");
teacher.teach();